/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/lesson1/HappyBackground`; params?: Router.UnknownInputParams; } | { pathname: `/components/lesson1/tower`; params?: Router.UnknownInputParams; } | { pathname: `/constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/controllers/auths`; params?: Router.UnknownInputParams; } | { pathname: `/controllers/querys`; params?: Router.UnknownInputParams; } | { pathname: `/firebase/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/views/authenthication/login`; params?: Router.UnknownInputParams; } | { pathname: `/views/authenthication/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `/views/authenthication/styles`; params?: Router.UnknownInputParams; } | { pathname: `/views/lessons/lesson1/L1FirstGame`; params?: Router.UnknownInputParams; } | { pathname: `/views/lessons/lesson1/L1SecondGame`; params?: Router.UnknownInputParams; } | { pathname: `/views/lessons/lesson1/L1ThirdGame`; params?: Router.UnknownInputParams; } | { pathname: `/views/profile/firstTimeRegister`; params?: Router.UnknownInputParams; } | { pathname: `/views/profile/main`; params?: Router.UnknownInputParams; } | { pathname: `/views/profile/styles`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/lesson1/HappyBackground`; params?: Router.UnknownOutputParams; } | { pathname: `/components/lesson1/tower`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/controllers/auths`; params?: Router.UnknownOutputParams; } | { pathname: `/controllers/querys`; params?: Router.UnknownOutputParams; } | { pathname: `/firebase/firebaseConfig`; params?: Router.UnknownOutputParams; } | { pathname: `/views/authenthication/login`; params?: Router.UnknownOutputParams; } | { pathname: `/views/authenthication/SignIn`; params?: Router.UnknownOutputParams; } | { pathname: `/views/authenthication/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/views/lessons/lesson1/L1FirstGame`; params?: Router.UnknownOutputParams; } | { pathname: `/views/lessons/lesson1/L1SecondGame`; params?: Router.UnknownOutputParams; } | { pathname: `/views/lessons/lesson1/L1ThirdGame`; params?: Router.UnknownOutputParams; } | { pathname: `/views/profile/firstTimeRegister`; params?: Router.UnknownOutputParams; } | { pathname: `/views/profile/main`; params?: Router.UnknownOutputParams; } | { pathname: `/views/profile/styles`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/lesson1/HappyBackground${`?${string}` | `#${string}` | ''}` | `/components/lesson1/tower${`?${string}` | `#${string}` | ''}` | `/constants/theme${`?${string}` | `#${string}` | ''}` | `/controllers/auths${`?${string}` | `#${string}` | ''}` | `/controllers/querys${`?${string}` | `#${string}` | ''}` | `/firebase/firebaseConfig${`?${string}` | `#${string}` | ''}` | `/views/authenthication/login${`?${string}` | `#${string}` | ''}` | `/views/authenthication/SignIn${`?${string}` | `#${string}` | ''}` | `/views/authenthication/styles${`?${string}` | `#${string}` | ''}` | `/views/lessons/lesson1/L1FirstGame${`?${string}` | `#${string}` | ''}` | `/views/lessons/lesson1/L1SecondGame${`?${string}` | `#${string}` | ''}` | `/views/lessons/lesson1/L1ThirdGame${`?${string}` | `#${string}` | ''}` | `/views/profile/firstTimeRegister${`?${string}` | `#${string}` | ''}` | `/views/profile/main${`?${string}` | `#${string}` | ''}` | `/views/profile/styles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/lesson1/HappyBackground`; params?: Router.UnknownInputParams; } | { pathname: `/components/lesson1/tower`; params?: Router.UnknownInputParams; } | { pathname: `/constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/controllers/auths`; params?: Router.UnknownInputParams; } | { pathname: `/controllers/querys`; params?: Router.UnknownInputParams; } | { pathname: `/firebase/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/views/authenthication/login`; params?: Router.UnknownInputParams; } | { pathname: `/views/authenthication/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `/views/authenthication/styles`; params?: Router.UnknownInputParams; } | { pathname: `/views/lessons/lesson1/L1FirstGame`; params?: Router.UnknownInputParams; } | { pathname: `/views/lessons/lesson1/L1SecondGame`; params?: Router.UnknownInputParams; } | { pathname: `/views/lessons/lesson1/L1ThirdGame`; params?: Router.UnknownInputParams; } | { pathname: `/views/profile/firstTimeRegister`; params?: Router.UnknownInputParams; } | { pathname: `/views/profile/main`; params?: Router.UnknownInputParams; } | { pathname: `/views/profile/styles`; params?: Router.UnknownInputParams; };
    }
  }
}
